#!/usr/bin/env bash
# Post-deploy smoke test for the compose stack.
#
#   scripts/smoke.sh                 # check the stack described by ./.env
#   scripts/smoke.sh --wait 90       # poll up to 90 s for the bridge to come up first
#   scripts/smoke.sh --url https://box.tailnet.ts.net   # MCP endpoint as clients see it
#
# Steps, in order:
#   1. bridge  GET /api/health   (inside the container: the bridge listens on loopback)
#   2. bridge  GET /api/ready    200 = paired and connected, 503 = waiting for the QR scan
#   3. mcp     GET /metrics      (skipped when WHATSAPP_MCP_METRICS=false)
#   4. mcp     POST /mcp initialize with the bearer token -> 200 + mcp-session-id
#
# Exit codes: 0 everything answers, 2 stack is up but not paired yet (scan the QR
# in `docker compose logs -f bridge`), 1 something is broken (the failing step
# says what to look at). Needs docker compose and curl on the host.
set -uo pipefail

cd "$(git rev-parse --show-toplevel 2>/dev/null || dirname "$0")/." || exit 1

WAIT=0
URL=""
while [ $# -gt 0 ]; do
  case "$1" in
    --wait) WAIT="${2:-0}"; shift 2 ;;
    --url) URL="${2:-}"; shift 2 ;;
    -h|--help) sed -n '2,17p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 1 ;;
  esac
done

# .env is KEY=VALUE lines (see .env.example); export them for the defaults below.
if [ -f .env ]; then
  set -a
  # shellcheck disable=SC1091
  . ./.env
  set +a
fi
MCP_PORT="${WHATSAPP_MCP_PORT:-8000}"
URL="${URL:-http://127.0.0.1:${MCP_PORT}}"
URL="${URL%/}"

red()   { printf '\033[31m%s\033[0m\n' "$*"; }
green() { printf '\033[32m%s\033[0m\n' "$*"; }
step()  { printf '\n== %s\n' "$*"; }
fail()  { red "FAIL: $1"; [ -n "${2:-}" ] && echo "      $2"; exit 1; }

compose() { docker compose "$@"; }
bridge_get() { # $1 path -> body on stdout, HTTP status in BRIDGE_STATUS
  # busybox wget: exit 0 with the body on a 2xx; on other statuses it prints
  # "server returned error: HTTP/1.1 503 Service Unavailable" and exits 1.
  local out rc
  out=$(compose exec -T bridge wget -qO- --header "Authorization: Bearer ${TOKEN}" "http://127.0.0.1:8080$1" 2>&1 </dev/null)
  rc=$?
  if [ "$rc" -eq 0 ]; then
    BRIDGE_STATUS=200
    printf '%s\n' "$out"
  else
    BRIDGE_STATUS=$(printf '%s\n' "$out" | sed -n 's/.*HTTP\/[0-9.]* \([0-9][0-9][0-9]\).*/\1/p' | tail -n1)
    [ -n "$BRIDGE_STATUS" ] || BRIDGE_STATUS="no response ($(printf '%s' "$out" | head -c 120))"
  fi
}

step "containers"
if ! compose ps --format '{{.Service}} {{.State}} {{.Health}}' 2>/dev/null | grep -q .; then
  fail "docker compose reports no containers" "run: docker compose up -d --build"
fi
compose ps --format '  {{.Service}}: {{.State}} {{.Health}}'

step "bridge token"
TOKEN="${WHATSAPP_BRIDGE_TOKEN:-}"
if [ -z "$TOKEN" ]; then
  TOKEN=$(compose exec -T bridge cat /app/store/.bridge-token 2>/dev/null </dev/null | tr -d '\r\n')
  [ -n "$TOKEN" ] || fail "no WHATSAPP_BRIDGE_TOKEN in .env and no /app/store/.bridge-token yet" "is the bridge running? docker compose logs bridge"
  echo "  using the token generated by the bridge (store/.bridge-token)"
else
  echo "  using WHATSAPP_BRIDGE_TOKEN from .env"
fi

step "1. bridge /api/health"
deadline=$(( $(date +%s) + WAIT ))
while :; do
  body=$(bridge_get /api/health)
  [ "${BRIDGE_STATUS:-}" = "200" ] && break
  if [ "$(date +%s)" -ge "$deadline" ]; then
    fail "bridge /api/health answered '${BRIDGE_STATUS:-no response}'" "docker compose logs --tail 50 bridge"
  fi
  sleep 3
done
echo "  $body"
case "$body" in
  *'"status":"ok"'*) PAIRED=yes ;;
  *) PAIRED=no ;;
esac

step "2. bridge /api/ready"
bridge_get /api/ready >/dev/null
case "${BRIDGE_STATUS:-}" in
  200) green "  connected to WhatsApp" ;;
  503) echo "  503: not connected (unpaired, or reconnecting)"; PAIRED=no ;;
  *) fail "unexpected /api/ready status '${BRIDGE_STATUS:-none}'" ;;
esac

step "3. mcp /metrics ($URL/metrics)"
if [ "$(printf '%s' "${WHATSAPP_MCP_METRICS:-true}" | tr '[:upper:]' '[:lower:]')" = "false" ]; then
  echo "  skipped (WHATSAPP_MCP_METRICS=false)"
else
  while :; do
    code=$(curl -sS -o /tmp/wamcp-metrics.$$ -w '%{http_code}' "$URL/metrics" 2>/dev/null || echo 000)
    [ "$code" = "200" ] || [ "$(date +%s)" -ge "$deadline" ] && break
    sleep 3 # the mcp container starts after the bridge is healthy
  done
  if [ "$code" = "200" ] && grep -q '^whatsapp_mcp_uptime_seconds' /tmp/wamcp-metrics.$$; then
    green "  ok ($(grep -c '^whatsapp_mcp_' /tmp/wamcp-metrics.$$) series)"
  else
    rm -f /tmp/wamcp-metrics.$$
    fail "GET $URL/metrics -> $code" "is the MCP port published (WHATSAPP_MCP_BIND / WHATSAPP_MCP_PORT) and the mcp container healthy?"
  fi
  rm -f /tmp/wamcp-metrics.$$
fi

step "4. mcp initialize ($URL/mcp)"
MCP_TOKEN="${WHATSAPP_MCP_TOKEN:-$TOKEN}"
hdrs=/tmp/wamcp-init-h.$$
body=/tmp/wamcp-init-b.$$
while :; do
  code=$(curl -sS -o "$body" -D "$hdrs" -w '%{http_code}' \
    -H "Authorization: Bearer ${MCP_TOKEN}" \
    -H 'Accept: application/json, text/event-stream' -H 'Content-Type: application/json' \
    -d '{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2025-03-26","capabilities":{},"clientInfo":{"name":"smoke","version":"0"}}}' \
    "$URL/mcp" 2>/dev/null || echo 000)
  [ "$code" != "000" ] || [ "$(date +%s)" -ge "$deadline" ] && break
  sleep 3
done
case "$code" in
  200)
    if grep -qi '^mcp-session-id:' "$hdrs"; then
      version=$(tr -d '\n' <"$body" | sed -n 's/.*"serverInfo":{[^}]*"version":"\([^"]*\)".*/\1/p')
      green "  ok (server version ${version:-unknown})"
    else
      rm -f "$hdrs" "$body"; fail "200 without mcp-session-id header" "is $URL really the MCP server?"
    fi ;;
  401) rm -f "$hdrs" "$body"; fail "401 Unauthorized" "token mismatch: WHATSAPP_MCP_TOKEN (or the bridge token when unset) differs from what the mcp container loaded; docker compose restart mcp after changing .env" ;;
  421) rm -f "$hdrs" "$body"; fail "421 Misdirected Request" "the Host you used (${URL#*://}) is not in WHATSAPP_MCP_ALLOWED_HOSTS" ;;
  000) rm -f "$hdrs" "$body"; fail "no answer from $URL/mcp" "port not published, wrong URL, or the mcp container is down (docker compose logs --tail 50 mcp)" ;;
  *) rm -f "$hdrs" "$body"; fail "unexpected status $code from $URL/mcp" ;;
esac
rm -f "$hdrs" "$body"

echo
if [ "$PAIRED" = "yes" ]; then
  green "All good: bridge paired and connected, MCP endpoint answering."
  exit 0
fi
echo "Stack is up but WhatsApp is not paired yet: run 'docker compose logs -f bridge' and scan the QR code."
exit 2
